networks:
  traefik:
    name: traefik
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-docker-trfk

include:
  - path: ./traefik/docker-compose.yaml
  - path: ./portainer/docker-compose.yaml
  - path: ./subversion/docker-compose.yaml

volumes:
  svn-root:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/subverse-data/svn-root

  gitlab-root:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/subverse-data/gitlab-root
