services:
  # Base SVN gateway with WEBDAV and svnserve services running
  svn_gateway:
    container_name: svn_gateway
    build:
      dockerfile: Dockerfile.svn-gateway
    restart: unless-stopped

    volumes:
      - svn-root:/var/svn
      - ./config/apache2-gateway:/etc/apache2
      - ./config/subversion:/etc/subversion

    environment:
      TZ: 'America/Chicago'

    networks:
      - traefik

    labels:
      # Enable as a 'traefik' service and configure
      traefik.enable: true
      traefik.docker.network: "traefik"

      # Subversion WebDAV service & router configuration for traefik
      traefik.http.services.svn_dav.loadbalancer.server.port: 80
      traefik.http.routers.svn_dav.service: svn_dav
      traefik.http.routers.svn_dav.rule: Host(`svndav.stoutrepodepot.com`)
      traefik.http.routers.svn_dav.entrypoints: websecure
      traefik.http.routers.svn_dav.tls.certresolver: myresolver
      traefik.http.routers.svn_dav.tls.domains[0].main: stoutrepotdepot.com
      traefik.http.routers.svn_dav.tls.domains[0].sans: "*.stoutrepodepot.com"

      # Subversion svnserve service & router configuration for traefik
      traefik.http.services.svn_serve.loadbalancer.server.port: 3690
      traefik.http.routers.svn_serve.service: svn_serve
      traefik.http.routers.svn_serve.rule: Host(`svnserve.stoutrepodepot.com`)
      traefik.http.routers.svn_serve.entrypoints: websecure
      traefik.http.routers.svn_serve.tls.certresolver: myresolver
      traefik.http.routers.svn_serve.tls.domains[0].main: stoutrepotdepot.com
      traefik.http.routers.svn_serve.tls.domains[0].sans: "*.stoutrepodepot.com"

  # Administrator service with PHP + 'svnadmin' (and no WEBDAV or svnserve)
  svn_admin:
    container_name: svn_admin
    build:
      dockerfile: Dockerfile.svn-admin
    restart: unless-stopped

    volumes:
      - svn-root:/var/svn
      - ./config/apache2-admin:/etc/apache2
      - ./config/subversion:/etc/subversion
      - ./config/php:/etc/php84
      - ./config/svnadmin:/opt/svnadmin/data

    environment:
      TZ: 'America/Chicago'

    networks:
      - traefik

    labels:
      # Enable as a 'traefik' service and configure
      traefik.enable: true
      traefik.docker.network: "traefik"

      # IF.SVNAdmin service & router configuration for traefik
      traefik.http.services.svnadmin.loadbalancer.server.port: 80
      traefik.http.routers.svnadmin.service: svnadmin
      traefik.http.routers.svnadmin.rule: Host(`svnadmin.stoutrepodepot.com`)
      traefik.http.routers.svnadmin.entrypoints: websecure
      traefik.http.routers.svnadmin.tls.certresolver: myresolver
      traefik.http.routers.svnadmin.tls.domains[0].main: stoutrepotdepot.com
      traefik.http.routers.svnadmin.tls.domains[0].sans: "*.stoutrepodepot.com"
