/**
 * seed.mjs - Load mock test data into the accountant database.
 *
 * Usage:
 *   npm run db:seed            Refuses to run if the database already has data
 *   npm run db:seed -- --force Wipes existing data first, then seeds (atomic swap)
 *
 * What gets created:
 *   - 40 users: 1 admin, 8 teachers, 31 students - ALL share the password
 *     "password123" (hash computed with bcrypt, same as the auth routes)
 *   - 4 classes: GDD 200 Intro to Game Development, GDD 325 Exploratory Game
 *     Design, CS 450 Game Design Capstone, CS 458 Software Engineering Practicum
 *   - 8 offerings (two per class), each taught by a different teacher
 *   - 24 projects (three per offering) with SVN/Git URLs and descriptions
 *   - Student-to-project assignments: every project gets 1-3 students so that
 *     student accounts can actually see data (students may only view projects
 *     they are assigned to). Some students end up unassigned on purpose, to
 *     exercise the empty state.
 *
 * Every generated class subject / number and offering term / section is
 * validated against the university rules in config/validation-rules.js via
 * shared/validate.js BEFORE anything is written. If any value fails validation
 * the script aborts; all writes happen in one transaction, so a failure never
 * leaves partial data behind.
 *
 * The dataset is generated by a seeded PRNG (env SEED, default 42), so repeated
 * runs produce the same users and values - handy for reproducible testing.
 */

import bcrypt from 'bcryptjs'
import { initDatabase } from '../server/db.js'
import {
  validateClassSubject,
  validateClassNumber,
  validateTerm,
  validateSection
} from '../shared/validate.js'

const TEST_PASSWORD = 'password123'
const SEED = Number(process.env.SEED ?? 42)
const FORCE = process.argv.includes('--force')

// --- Deterministic PRNG (mulberry32) -----------------------------------------
function mulberry32 (seed) {
  let a = seed >>> 0
  return function () {
    a |= 0
    a = (a + 0x6D2B79F5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

const rand = mulberry32(SEED)
function shuffle (arr) {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

// --- Data pools ---------------------------------------------------------------
const FIRST_NAMES = [
  'Ava', 'Liam', 'Maya', 'Noah', 'Zoe', 'Ethan', 'Isla', 'Owen', 'Ruby', 'Caleb',
  'Nina', 'Felix', 'Tara', 'Jonas', 'Priya', 'Marcus', 'Elle', 'Diego', 'Hana', 'Victor',
  'Sofia', 'Andre', 'Lena', 'Kofi', 'Mira', 'Theo', 'Yuki', 'Ravi', 'Clara', 'Dmitri',
  'Aisha', 'Bruno', 'Freya', 'Gustav', 'Imani', 'Jorge', 'Keiko', 'Luca', 'Nadia', 'Oscar'
]

const LAST_NAMES = [
  'Adler', 'Bennett', 'Chen', 'Delgado', 'Ellison', 'Foster', 'Grant', 'Haddad', 'Ibarra', 'Jensen',
  'Kowalski', 'Lindqvist', 'Moreau', 'Nguyen', 'Ortiz', 'Petrov', 'Quintero', 'Reyes', 'Sato', 'Tanaka',
  'Ueda', 'Vargas', 'Whitfield', 'Xu', 'Yamamoto', 'Zhang', 'Brooks', 'Carter', 'Dawson', 'Evans',
  'Fischer', 'Gallagher', 'Hughes', 'Ito', 'Johansson', 'Klein', 'Lambert', 'Mercer', 'Novak', 'Osei'
]

/** Terms that pass the offeringTerm rule (recent, relative to "now"). */
const TERMS = ['FALL25', 'SPRING26', 'SUMMER26', 'FALL26']

/** Sections that pass the offeringSection rule. */
const SECTIONS = ['101', '102', '103', '104', '105', '106']

const CLASSES = [
  { subject: 'GDD', number: '200', title: 'Intro to Game Development' },
  { subject: 'GDD', number: '325', title: 'Exploratory Game Design' },
  { subject: 'CS', number: '450', title: 'Game Design Capstone' },
  { subject: 'CS', number: '458', title: 'Software Engineering Practicum' }
]

/** Six candidate project titles per class; each offering takes three. */
const PROJECT_TITLES = [
  ['Puzzle Garden', 'Dungeon Crawl', 'Racing Rumble', 'Pinball Panic', 'Space Miner', 'Tower Defense Tycoon'],
  ['One Button Odyssey', 'Cardboard Kingdom', 'Physics Playground', 'Narrative Sandbox', 'Maze Runner Prototype', 'Co-op Rescue'],
  ['Realm of Echoes', 'Starbound Vanguard', 'Iron Harvest', 'Chronicle of Ash', 'Velocity Zero', 'Mystic Realms'],
  ['Build Pipeline Studio', 'Code Review Trainer', 'Test Automation Lab', 'Release Manager Sim', 'DevOps Dashboard', 'CI Sandbox']
]

// --- Generate the dataset (in memory, before touching the database) -----------
/** 39 unique first/last name pairs for teachers + students. */
const namePairs = shuffle(FIRST_NAMES.flatMap(first => LAST_NAMES.map(last => [first, last])))

function makeAccount (index, type) {
  const [firstName, lastName] = namePairs[index]
  let username = `${firstName[0].toLowerCase()}${lastName.toLowerCase()}`
  let n = 2
  while (usedUsernames.has(username)) username = `${firstName[0].toLowerCase()}${lastName.toLowerCase()}${n++}`
  usedUsernames.add(username)
  return {
    username,
    first_name: firstName,
    last_name: lastName,
    email: `${firstName}.${lastName}@university.edu`,
    type
  }
}

const usedUsernames = new Set(['admin'])

const admin = {
  username: 'admin',
  first_name: 'Ava',
  last_name: 'Root',
  email: 'admin@university.edu',
  type: 'ADMIN'
}
usedUsernames.add(admin.username)

const teachers = Array.from({ length: 8 }, (_, i) => makeAccount(i, 'TEACHER'))
const students = Array.from({ length: 31 }, (_, i) => makeAccount(8 + i, 'STUDENT'))

/** Two offerings per class: distinct terms and sections within the class. */
const offerings = [] // { classIndex, term, section }
CLASSES.forEach((cls, ci) => {
  const [termA, termB] = shuffle(TERMS).slice(0, 2)
  const [sectionA, sectionB] = shuffle(SECTIONS).slice(0, 2)
  offerings.push({ classIndex: ci, term: termA, section: sectionA })
  offerings.push({ classIndex: ci, term: termB, section: sectionB })
})

/** One teacher per offering (8 teachers, 8 offerings - a perfect matching). */
const shuffledTeachers = shuffle(teachers)

/** Three projects per offering; titles are unique within each class. */
const projects = [] // { offeringIndex, title, slug, subversion_url, git_url, description }
const usedSlugs = new Set()
offerings.forEach((offering, oi) => {
  const cls = CLASSES[offering.classIndex]
  const titles = shuffle(PROJECT_TITLES[offering.classIndex]).slice(0, 3)
  for (const title of titles) {
    const slug = `${title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${offering.term.toLowerCase()}-${offering.section}`
    if (usedSlugs.has(slug)) throw new Error(`Generated duplicate project slug "${slug}"`)
    usedSlugs.add(slug)
    projects.push({
      offeringIndex: oi,
      title,
      slug,
      subversion_url: `https://svn.university.edu/courses/${cls.subject}${cls.number}/${offering.term.toLowerCase()}/${offering.section}/${slug}`,
      git_url: rand() < 0.5 ? `https://git.university.edu/courses/${cls.subject}${cls.number}/${slug}.git` : null,
      description: `${title}: team project for ${cls.subject} ${cls.number} (${offering.term}, section ${offering.section}).`
    })
  }
})

/** Assign 1-3 distinct students to every project (a student may join several). */
const assignments = [] // { studentIndex, projectIndex }
projects.forEach((project, pi) => {
  const count = 1 + Math.floor(rand() * 3) // 1..3
  for (const si of shuffle(students.map((_, i) => i)).slice(0, count)) {
    assignments.push({ studentIndex: si, projectIndex: pi })
  }
})

// --- Validate everything against the university rules -------------------------
const validationErrors = []
for (const cls of CLASSES) {
  const subjectError = validateClassSubject(cls.subject)
  if (subjectError) validationErrors.push(subjectError)
  const numberError = validateClassNumber(cls.number)
  if (numberError) validationErrors.push(numberError)
}
for (const offering of offerings) {
  const termError = validateTerm(offering.term)
  if (termError) validationErrors.push(termError)
  const sectionError = validateSection(offering.section)
  if (sectionError) validationErrors.push(sectionError)
}
if (validationErrors.length > 0) {
  console.error('Generated data failed the university validation rules:')
  for (const err of validationErrors) console.error(`  - ${err}`)
  process.exit(1)
}

// --- Write it all -------------------------------------------------------------
const db = initDatabase()

let existingCount
try {
  existingCount = await db.user.count()
} catch (err) {
  console.error(`Could not read the database: ${err.message}`)
  console.error('Make sure the schema has been applied first (npm run db:push).')
  process.exit(1)
}

if (existingCount > 0 && !FORCE) {
  console.error(`Database already contains ${existingCount} user(s).`)
  console.error('Re-run with --force to wipe and reseed, or run "npm run db:clear" first.')
  process.exit(1)
}

const teacherOf = {} // offering index -> teacher account
shuffledTeachers.forEach((teacher, i) => {
  teacherOf[i] = teacher
})

let result
try {
  result = await db.$transaction(async tx => {
    if (existingCount > 0) {
      // Wipe in foreign-key order so the reseed is a clean atomic swap.
      await tx.assignment.deleteMany()
      await tx.project.deleteMany()
      await tx.offering.deleteMany()
      await tx.class.deleteMany()
      await tx.user.deleteMany()
    }

    const passwordHash = await bcrypt.hash(TEST_PASSWORD, 10)

    // Users
    const userRows = []
    for (const account of [admin, ...teachers, ...students]) {
      userRows.push(await tx.user.create({
        data: {
          username: account.username,
          first_name: account.first_name,
          last_name: account.last_name,
          email: account.email,
          password_hash: passwordHash,
          type: account.type
        }
      }))
    }
    const adminRow = userRows[0]
    const teacherRows = userRows.slice(1, 9)
    const studentRows = userRows.slice(9)

    // Classes
    const classRows = []
    for (const cls of CLASSES) {
      classRows.push(await tx.class.create({
        data: { subject: cls.subject, number: cls.number, title: cls.title }
      }))
    }

    // Offerings
    const offeringRows = []
    for (let oi = 0; oi < offerings.length; oi++) {
      const offering = offerings[oi]
      offeringRows.push(await tx.offering.create({
        data: {
          class_id: classRows[offering.classIndex].id,
          teacher_id: teacherRows[oi].id,
          term: offering.term,
          section: offering.section
        }
      }))
    }

    // Projects
    const projectRows = []
    for (const project of projects) {
      projectRows.push(await tx.project.create({
        data: {
          offering_id: offeringRows[project.offeringIndex].id,
          title: project.title,
          slug: project.slug,
          subversion_url: project.subversion_url,
          git_url: project.git_url,
          description: project.description
        }
      }))
    }

    // Assignments
    if (assignments.length > 0) {
      await tx.assignment.createMany({
        data: assignments.map(a => ({
          student_id: studentRows[a.studentIndex].id,
          project_id: projectRows[a.projectIndex].id
        }))
      })
    }

    // Sanity check: the shared hash really matches the test password.
    if (!(await bcrypt.compare(TEST_PASSWORD, passwordHash))) {
      throw new Error('Internal error: seeded password hash does not match the test password')
    }

    return { adminRow, teacherRows, studentRows }
  })
} catch (err) {
  console.error('Seeding failed, database left unchanged:', err.message)
  process.exit(1)
}

// Print a friendly summary with example credentials.
console.log('')
console.log(`Seeded ${1 + teachers.length + students.length} users (1 admin, ${teachers.length} teachers, ${students.length} students),`)
console.log(`${CLASSES.length} classes, ${offerings.length} offerings, ${projects.length} projects, ${assignments.length} assignments.`)
console.log(`All accounts use the password: ${TEST_PASSWORD}`)
console.log('')
console.log('Example logins:')
console.log(`  admin:    ${result.adminRow.username}`)
result.teacherRows.forEach((t, i) => {
  const off = offerings[i]
  const cls = CLASSES[off.classIndex]
  console.log(`  teacher:  ${t.username}  (teaches ${cls.subject} ${cls.number} - ${off.term}, section ${off.section})`)
})
for (const s of result.studentRows.slice(0, 5)) {
  const n = assignments.filter(a => result.studentRows[a.studentIndex].id === s.id).length
  console.log(`  student:  ${s.username}  (${n} project assignment${n === 1 ? '' : 's'})`)
}
if (result.studentRows.length > 5) {
  console.log(`  ... and ${result.studentRows.length - 5} more students`)
}

process.exit(0)
