services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:sts
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

    environment:
      TZ: 'America/Chicago'

    networks:
      - traefik

    labels:
      # Enable as a 'traefik' service and configure
      traefik.enable: true
      traefik.docker.network: "traefik"
      traefik.http.services.portainer.loadbalancer.server.port: 9000

      # Portainer service & router configuration for traefik
      traefik.http.routers.portainer.service: portainer
      # traefik.http.routers.portainer.rule: PathPrefix(`/dock`)
      traefik.http.routers.portainer.rule: Host(`dock.subverse`)
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.routers.portainer.tls: true
      # traefik.http.middlewares.portainer-strip.stripprefix.prefixes: /dock
      # traefik.http.routers.portainer.middlewares: portainer-strip
